#!/bin/bash
  2
  3 #Author: Caroline
  4 #Date: August 2022
  5
  6
  7 ## Docker-compose Installation script
  8
  9 echo " Are you sure you want to install Docker-compose on your server?"
 10 read ya
 11
 12 if [ ya=yes ]
 13
 14 then
 15
 16 echo " Proceed and run the next command"
 17
 18 else
 19
 20 exit 5
 21
 22 fi
 23
 24 sudo curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
 25
 26 sleep 4
 27
 28 if [ $? -eq 0 ]
 29
 30 then
 31
 32 echo " Run the next command"
 33
 34 chmod +x /usr/local/bin/docker-compose
 else
 37
 38 exit 1
 39
 40 fi
 41
 42 sleep 3
 43
 44 docker-compose --version

 if [ $? -eq 0 ]
 47
 48 then
 49
 50 echo " Docker compose was installed successfully, there is no need to run the next command"
 51
 52 else
 53
 54 echo " Run the following command"
 55
 56 sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
 57
 58 fi
 sleep 3
 61
 62 docker-compose --version
 63
 64 if [ $? -eq 0 ]
 65
 66 then
 67
 68 echo " Docker-compose was installed successfully"
 69
 70 else
 71
 72 echo " Check your commands and try again"
    fi 



