#!/bin/bash
  
#Author: Caroline
#Date: August 2022

## Docker-compose Installation script

echo " Are you sure you want to install Docker-compose on your server?"
read ya

if [ ya=yes ]

then

echo " Proceed and run the next command"

else


exit 5

sudo curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

sleep 4

if [ $? -eq 0 ]

then

echo " Run the next command"

chmod +x /usr/local/bin/docker-compose
else
exit 1
fi
sleep 3
docker-compose --version

if [ $? -eq 0 ]
then

echo " Docker compose was installed successfully, there is no need to run the next command"

else

echo " Run the following command"

sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

fi

sleep 3

docker-compose --version

if [ $? -eq 0 ]

then

echo " Docker-compose was installed successfully"

else

echo " Check your commands and try again"

fi 



